// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtt8rxv_cNUk8EF00C6rRVgEaKn-nEjwY',
    appId: '1:212560735912:web:4db8171afeab16cc179c9d',
    messagingSenderId: '212560735912',
    projectId: 'doyoudo-35684',
    authDomain: 'doyoudo-35684.firebaseapp.com',
    storageBucket: 'doyoudo-35684.firebasestorage.app',
    measurementId: 'G-YYP9YZSWQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRtG_gICmal93-xRkMZLf8Cdt7U0uuotw',
    appId: '1:212560735912:android:165413d8f93ccc7a179c9d',
    messagingSenderId: '212560735912',
    projectId: 'doyoudo-35684',
    storageBucket: 'doyoudo-35684.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYOgHVj41PrhuUI3AMHlpNFhMs0TD3Et8',
    appId: '1:212560735912:ios:10b36ab57c4c60de179c9d',
    messagingSenderId: '212560735912',
    projectId: 'doyoudo-35684',
    storageBucket: 'doyoudo-35684.firebasestorage.app',
    iosBundleId: 'com.example.doYouDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYOgHVj41PrhuUI3AMHlpNFhMs0TD3Et8',
    appId: '1:212560735912:ios:10b36ab57c4c60de179c9d',
    messagingSenderId: '212560735912',
    projectId: 'doyoudo-35684',
    storageBucket: 'doyoudo-35684.firebasestorage.app',
    iosBundleId: 'com.example.doYouDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtt8rxv_cNUk8EF00C6rRVgEaKn-nEjwY',
    appId: '1:212560735912:web:b6de36864ba5fbdb179c9d',
    messagingSenderId: '212560735912',
    projectId: 'doyoudo-35684',
    authDomain: 'doyoudo-35684.firebaseapp.com',
    storageBucket: 'doyoudo-35684.firebasestorage.app',
    measurementId: 'G-7BS96C7DCP',
  );
}
